[package]
name = "resource_info_table_macro"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
phf.workspace = true
proc-macro2.workspace = true
syn.workspace = true

[build-dependencies]
phf_codegen.workspace = true
