[workspace]
members = [
    "primeapi-rs",
        "primeapi-rs/primeapi_macros",
    "rel_loader",
    "rel_patches",
]
resolver = "2"

[profile.dev]
panic = "abort"
lto = true
codegen-units = 1

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 's'
