[package]
name = "dol_linker"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[dependencies]
clap.workspace = true
enum-map = "0.6"
goblin = "0.1"
memmap.workspace = true
scroll = { version = "0.10", features = ["derive"] }
snafu = "0.6"
