[package]
name = "structs"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[dependencies]
auto_struct_macros.workspace = true
resource_info_table.workspace = true
reader_writer.workspace = true
serde.workspace = true
