[package]
name = "ppcasm_macro"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
