[package]
name = "nod_wrapper"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[dependencies]
cpp = "0.5"
reader_writer.workspace = true

[build-dependencies]
# cmake = "0.1"
cpp_build = "0.5"
cc.workspace = true
