[package]
name = "ppcasm"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[dependencies]
byteorder.workspace = true
generic-array.workspace = true
ppcasm_macro = { path = "ppcasm_macro" }
