[package]
name = "dol_symbol_table_macro"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
phf.workspace = true

[build-dependencies]
phf_codegen.workspace = true
