[package]
name = "json_data"
version = "0.1.0"
authors = ["toasterparty <toasterparty@derpymail.org>"]
edition = "2021"

[build-dependencies]
json_strip = { path = "../json_strip" }
minify = "1.3.0"
walkdir = "2"
