[package]
name = "resource_info_table"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

[dependencies]
reader_writer.workspace = true
resource_info_table_macro = { path = "resource_info_table_macro" }
